var XRegExp = require('xregexp').XRegExp;
var messageFormat = require('./messageformat');

var create = function(doc, nsPrefix, lang, id) {
  var ret = '';

  var ns = _getLngNs(nsPrefix, lang, doc);

  ret += "// Content below is autogenerated by gcin\n";
  ret += "// usually there is no reason to edit it manually\n\n";
  ret += "goog.provide('" + ns + "');\n";
  ret += "\n";

  doc.msgs.forEach(function(msg, pos) {
    var msgName = ["MSG", (lang || 'self').toUpperCase(), msg.id.toUpperCase(), id, pos].join('_');

    // if lang is not defined create js with sourse language
    var translation = lang ? msg.translation : msg.body;

    if (msg.type == 'msgf') {
      translation = translation.replace(/\n\s*/g, '').replace(/\<%\s*@space\s*%\>/g, ' ');
      var mf = messageFormat(translation.replace(/\{\$(.+?)\}/g, 'REPLACEMENT'), lang || doc.source);
    } else {
      translation.replace(/\<%\s*@space\s*%\>/g, ' ');
    }

    var props = {};
    XRegExp.forEach(translation, /\{\$(.+?)\}/, function (match, i) {
      props[match[1]] = true;
    });

    var properties = [];
    for (var name in props) {
      properties.push(name);
    }

    ret += "\n";
    if (properties.length > 0) {
      ret += "/** @param {Object} options */\n";
      ret += ns + "." + msg.id + " = function(options) {\n";
    } else {
      ret += ns + "." + msg.id + " = function() {\n";
    }

    ret += "  /**  @desc " + (msg.desc || msg.id) + " */\n";
    ret += "  var " + msgName + " = goog.getMsg(";

    var multiline = translation.indexOf('\n') != -1;
    var spaces = '';
    if (multiline) {
      spaces += '  ';
      ret += "\n" + spaces + "  '" + translation.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, "' +\n" + spaces + "  '") + "'\n";
    } else {
      ret += "'" + translation.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
    }

    if (properties.length > 0) {
      ret += ", {\n";
      properties.forEach(function(prop, pos) {
        if (pos > 0) {
          ret += ",\n";
        }
        ret += spaces + "    '" + prop.replace(/'/g, "\\'") + "': options";
        if ((/^[_a-zA-Z][_a-zA-Z0-9]*$/).test(prop)) {
          ret += '.' + prop;
        } else {
          ret += "['" + prop.replace(/'/g, "\\'") + "']";
        }
      });
      ret += "\n" + spaces + "  }";
    }

    if (multiline) {
      ret += spaces + ");\n";
    } else {
      ret += ");\n";
    }

    ret += "  return " + msgName + ";\n";
    ret += "};\n";
  });

  return ret;
};


var createUnion = function(doc, nsPrefix, langs) {
  var ret = '';

  ret += "// Content below is autogenerated by gcin\n";
  ret += "// usually there is no reason to edit it manually\n\n";

  var ns = doc.ns;
  if (nsPrefix) {
    ns = [nsPrefix, doc.ns].join('.');
  }

  ret += "goog.provide('" + ns + "');\n";
  langs.forEach(function(lang, pos) {
    var lngNs = _getLngNs(nsPrefix, lang, doc);
    ret += "goog.require('" + lngNs + "');\n";
  });
  ret += "\n";

  langs.forEach(function(lang, pos) {
    var lngNs = _getLngNs(nsPrefix, lang, doc);
    if (pos > 0) {
      ret += "\n";
    }
    ret += "if (goog.LOCALE == '" + lang + "') {\n";
    ret += "  " + ns + " = " + lngNs + ";\n";
    ret += "}\n";
  });

  return ret;
};

var _getLngNs = function(nsPrefix, lang, doc) {
  var ns = ['lang', (lang || doc.source), doc.ns].join('.');
  if (nsPrefix) {
    ns = [nsPrefix, 'lang', (lang || doc.source), doc.ns].join('.');
  }

  return ns;
};


module.exports = {
  create: create,
  createUnion: createUnion
};